from .api_tokens_management import (
    ApiTokenDto,
    ApiTokenScopeEndpointDto,
    ApiTokenScopeResourceDto,
    CreateApiTokenRequestDto,
    CreateApiTokenResponseDto,
    DeleteApiTokenResponseDto,
    DocsInfoDto,
    FindAllApiTokensResponseDto,
    GetApiTokenScopesResponseDto,
)
from .auth import (
    GetStatusResponseDto,
    LoginRequestDto,
    LoginResponseDto,
    RegisterRequestDto,
    RegisterResponseDto,
    StatusResponseDto,  # Legacy alias
    TelegramCallbackRequestDto,
    TelegramCallbackResponseDto,
    LoginTelegramRequestDto,  # Legacy alias
    OAuth2AuthorizeRequestDto,
    OAuth2AuthorizeResponseDto,
    OAuth2CallbackRequestDto,
    OAuth2CallbackResponseDto,
    VerifyPasskeyAuthenticationRequestDto,
    VerifyPasskeyAuthenticationResponseDto,
    GetPasskeyAuthenticationOptionsResponseDto,
)
from .bandwidthstats import (
    GetNodeUserUsageByRangeResponseDto,
    GetNodesRealtimeUsageResponseDto,
    GetNodesUsageByRangeResponseDto,
    GetUserUsageByRangeResponseDto,
    NodeRealtimeUsageResponseDto,
    NodeUsageResponseDto,
    NodesRealtimeUsageResponseDto,  # Legacy alias
    NodesUsageResponseDto,  # Legacy alias
    GetLegacyStatsUserUsageResponseDto,
    GetLegacyStatsNodesUsersUsageResponseDto,
    GetStatsNodesRealtimeUsageResponseDto,
    GetStatsNodesUsageResponseDto,
    GetStatsNodeUsersUsageResponseDto,
    GetStatsNodesUsersUsageRequestDto,
    GetStatsNodesUsersUsageResponseDto,
    GetStatsUserUsageResponseDto,

    # Data Models
    LegacyUserUsageItem,
    LegacyNodeUserUsageItem,
    NodeRealtimeUsageItem,
    TopNodeItem,
    TopUserItem,
    TopNodesUserItem,
    NodeSeriesItem,
    StatsNodesUsageData,
    StatsNodeUsersUsageData,
    StatsNodesUsersUsageData,
    StatsUserUsageData,
)
from .config_profiles import (
    ConfigProfileDto,
    GetConfigProfilesTagsResponseDto,
    SetConfigProfilesTagsRequestDto,
    SetConfigProfilesTagsResponseDto,
    CreateConfigProfileRequestDto,
    CreateConfigProfileResponseDto,
    DeleteConfigProfileResponseDto,
    GetAllConfigProfilesResponseDto,
    GetAllConfigProfilesResponsePaginated,
    GetAllInboundsResponseDto,
    GetConfigProfileByUuidResponseDto,
    GetInboundsByProfileUuidResponseDto,
    InboundDto,
    NodesProfileDto,
    ReorderConfigProfileItem,
    ReorderConfigProfilesRequestDto,
    ReorderConfigProfilesResponseDto,
    UpdateConfigProfileRequestDto,
    UpdateConfigProfileResponseDto,
)
from .hosts import (
    CreateHostInboundData,
    HostInternalSquadsDto,
    HostMapperCopyOp,
    HostMapperDto,
    HostMapperOp,
    HostMapperSetOp,
    HostMapperUnsetOp,
    HostTag,
    CreateHostRequestDto,
    CreateHostResponseDto,
    DeleteHostResponseDto,
    GetAllHostsResponseDto,
    GetOneHostResponseDto,
    HostInboundData,
    HostResponseDto,
    HostsResponseDto,  # Legacy alias
    ReorderHostItem,
    ReorderHostRequestDto,
    ReorderHostResponseDto,
    UpdateHostRequestDto,
    UpdateHostResponseDto,
    GetAllHostTagsResponseDto,
)
from .hosts_bulk_actions import (
    BulkDeleteHostsResponseDto,
    BulkDisableHostsResponseDto,
    BulkEnableHostsResponseDto,
    UpdateManyHostsRequestDto,
    UpdateManyHostsResponseDto,
)
from .hwid import (
    CreateHWIDUser,  # Legacy alias
    PlatformStatItem,
    CreateUserHwidDeviceRequestDto,
    CreateUserHwidDeviceResponseDto,
    DeleteUserHwidDeviceRequestDto,
    DeleteUserHwidDeviceResponseDto,
    GetUserHwidDevicesResponseDto,
    HWIDDeleteRequest,  # Legacy alias
    HWIDUserResponseDto,  # Legacy alias
    HWIDUserResponseDtoList,  # Legacy alias
    GetHwidStatisticsResponseDto,
    DeleteUserAllHwidDeviceRequestDto,
    GetTopUsersByHwidDevicesResponseDto,
    TopUserByHwidDevicesDto,
    TopUsersByHwidDevicesData,
)
from .inbounds import (
    AllInboundsData,
    FullInboundResponseDto,
    FullInboundStatistic,
    FullInboundsResponseDto,
    GetAllInboundsResponseDto,
    GetFullInboundsResponseDto,
    GetInboundsByProfileUuidResponseDto,
    GetInboundsResponseDto,
    InboundResponseDto,
    InboundsByProfileData,
    InboundsResponseDto,  # Legacy alias
)
from .inbounds_bulk_actions import (
    AddInboundToNodesResponseDto,
    AddInboundToUsersResponseDto,
    RemoveInboundFromNodesResponseDto,
    RemoveInboundFromUsersResponseDto,
)
from .infra_billing import (
    CreateInfraBillingHistoryRecordRequestDto,
    CreateInfraBillingHistoryRecordResponseDto, 
    CreateInfraBillingNodeRequestDto,
    CreateInfraBillingNodeResponseDto,
    CreateInfraProviderRequestDto,
    CreateInfraProviderResponseDto,
    DeleteInfraBillingHistoryRecordByUuidResponseDto,  
    DeleteInfraBillingNodeByUuidResponseDto,  # ПЕРЕИМЕНОВАНА (было DeleteInfraBillingNodeResponseDto)
    DeleteInfraProviderByUuidResponseDto,  # ПЕРЕИМЕНОВАНА (было DeleteInfraProviderResponseDto)
    GetInfraBillingHistoryRecordsResponseDto,  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingHistoryResponseDto)
    GetInfraBillingNodesResponseDto,  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingNodesResponseDto)
    GetInfraProvidersResponseDto,  # ПЕРЕИМЕНОВАНА (было GetAllInfraProvidersResponseDto)
    GetInfraBillingHistoryByUuidResponseDto,
    GetInfraBillingNodeByUuidResponseDto,
    GetInfraProviderByUuidResponseDto,
    InfraBillingHistoryDto,
    InfraBillingNodeDto,
    InfraProviderDto,
    NodeDto,
    UpdateInfraBillingNodeRequestDto,
    UpdateInfraBillingNodeResponseDto,
    UpdateInfraProviderRequestDto,
    UpdateInfraProviderResponseDto,
    DeleteInfraBillingNodeResponseDto,  # LEGACY
    DeleteInfraProviderResponseDto,  # LEGACY
    GetAllInfraBillingHistoryResponseDto,  # LEGACY
    GetAllInfraBillingNodesResponseDto,  # LEGACY
    GetAllInfraProvidersResponseDto,  # LEGACY
)
from .internal_squads import (
    GetInternalSquadsTagsResponseDto,
    SetInternalSquadsTagsRequestDto,
    SetInternalSquadsTagsResponseDto,
    AddUsersToInternalSquadRequestDto,
    AddUsersToInternalSquadResponseDto,
    CreateInternalSquadRequestDto,
    CreateInternalSquadResponseDto,
    DeleteInternalSquadResponseDto,
    DeleteUsersFromInternalSquadRequestDto,
    DeleteUsersFromInternalSquadResponseDto,
    GetAllInternalSquadsResponseDto,
    GetInternalSquadByUuidResponseDto,
    InternalSquadDto,
    ReorderInternalSquadItem,
    ReorderInternalSquadsRequestDto,
    ReorderInternalSquadsResponseDto,
    UpdateInternalSquadRequestDto,
    UpdateInternalSquadResponseDto,
    GetInternalSquadAccessibleNodesResponseDto,
)
from .keygen import GetNodeSecretKeyResponseDto
from .nodes import (
    CreateNodeRequestDto,
    NodeIpDto,
    CreateNodeResponseDto,
    DeleteNodeResponseDto,
    DisableNodeResponseDto,
    EnableNodeResponseDto,
    ExcludedInbounds,
    GetAllNodesResponseDto,
    GetAllNodesTagsResponseDto,
    GetOneNodeResponseDto,
    NodeConfigProfileDto,
    NodeConfigProfileRequestDto,
    NodeResponseDto,
    NodesResponseDto,  # Legacy alias
    ReorderNodeRequestDto,
    ReorderNodeResponseDto,
    RestartAllNodesResponseDto,
    RestartNodeResponseDto,
    UpdateNodeRequestDto,
    UpdateNodeResponseDto,
    RestartAllNodesRequestDto, # Legacy alias,
    RestartAllNodesRequestBodyDto,
    RestartNodeRequestBodyDto,
    ResetNodeTrafficRequestDto,
    ResetNodeTrafficResponseDto,
    ProfileModificationRequestDto,
    ProfileModificationResponseDto,
    NodeBulkActionType,
    NodesBulkActionsRequestDto,
    NodesBulkActionsResponseDto,
    BulkNodesUpdateRequestDto,
    BulkNodesUpdateFieldsDto,
    BulkNodesUpdateResponseDto,
)
from .nodes_usage_history import (
    GetNodeUserUsageByRangeResponseDto,
    GetNodesUsageByRangeResponseDto,
    GetUserAccessibleNodesResponseDto,
    NodeInfoDto,
    NodeUsageDto,
    UserUsageDto,
)
from .subscription import (
    GetAllSubscriptionsResponseDto,
    GetSubscriptionByUsernameResponseDto,
    GetSubscriptionInfoResponseDto,
    SubscriptionInfoResponseDto,  # Legacy alias
    UserSubscription,
    GetRawSubscriptionByShortUuidResponseDto,
    RawSettings,
    GetSubscriptionByShortUUIDResponseDto,
    GetSubscriptionByUUIDResponseDto,
    GetConnectionKeysByUuidResponseDto,
)
from .subscriptions_settings import (
    ResponseModificationEncryption,
    GetSubscriptionSettingsResponseDto,
    ResponseModificationHeader,
    ResponseModifications,
    ResponseRule,
    ResponseRuleCondition,
    ResponseRules,
    ResponseRulesSettings,
    SubscriptionSettingsResponseDto,
    SubscriptionType,
    UpdateSubscriptionSettingsRequestDto,
    UpdateSubscriptionSettingsResponseDto,
    CustomRemarksDto,
    HwidSettingsDto,
    # Backward compatibility aliases
    CustomRemarks,
    HwidSettings,
)
from .subscriptions_template import (
    GetSubscriptionTemplatesTagsResponseDto,
    SetSubscriptionTemplatesTagsRequestDto,
    SetSubscriptionTemplatesTagsResponseDto,
    CreateSubscriptionTemplateRequestDto,
    CreateSubscriptionTemplateResponseDto,
    DeleteSubscriptionTemplateResponseDto,
    GetTemplatesResponseDto,
    TemplateInfoDto,
    GetTemplateResponseDto,
    ReorderTemplateItem,
    ReorderSubscriptionTemplatesRequestDto,
    ReorderSubscriptionTemplatesResponseDto,
    TemplateResponseDto,
    UpdateTemplateRequestDto,
    UpdateTemplateResponseDto,
)
from .system import (
    RuntimeMetric,
    GetStatsDigestResponseDto,
    GetHttpStatsResponseDto,
    GetConfigurationResponseDto,
    ConfigurationNotifications,
    ConfigurationService,
    ConfigurationMisc,
    BandwidthStatistic,
    BandwidthStatisticResponseDto,
    CPUStatistic,
    GetBandwidthStatsResponseDto,
    GetNodesStatisticsResponseDto,
    GetRemnawaveHealthResponseDto,
    GetStatsResponseDto,
    MemoryStatistic,
    NodeStatistic,
    NodesStatisticResponseDto,
    OnlineStatistic,
    StatisticResponseDto,
    StatusCounts,
    UsersStatistic,
    GetNodesMetricsResponseDto,
    GetX25519KeyPairResponseDto,
    X25519KeyPair,
    DebugSrrMatcherRequestDto,
    DebugSrrMatcherResponseDto,
    GetMetadataResponseDto,
    GetRecapResponseDto,
    RecapThisMonth,
    RecapTotal,
)
from .users import (
    # Request body DTOs (v3.0.0)
    CreateUserBodyDto,
    UpdateUserBodyDto,
    ExtendUserBodyDto,
    RevokeUserSubscriptionBodyDto,
    ResolveUserBodyDto,
    ResolveUserResponseDto,

    # Response DTOs
    UserResponseDto,
    UsersResponseDto,
    GetUsersResponseDto,
    GetUsersStreamResponseDto,
    UsersStreamData,
    GetUsersTagsResponseDto,
    TagsResponseDto,
    GetUserSubscriptionRequestHistoryResponseDto,
    SubscriptionRequestsResponseData,

    # Data DTOs
    UserTrafficDto,
    ActiveInternalSquadDto,
    SubscriptionRequestRecord,
    HappCrypto,
    UserActiveInboundsDto,
    UserLastConnectedNodeDto,
)

from .users_bulk_actions import (
    BulkAllExtendExpirationDateRequestDto, 
    BulkAllExtendExpirationDateResponseDto, 
    BulkAllResetTrafficUsersResponseDto,
    BulkAllUpdateUsersRequestDto,
    BulkAllUpdateUsersResponseDto,
    BulkDeleteUsersByStatusRequestDto, 
    BulkDeleteUsersByStatusResponseDto, 
    BulkDeleteUsersRequestDto, 
    BulkDeleteUsersResponseDto, 
    BulkEventResponseData, 
    BulkExtendExpirationDateRequestDto, 
    BulkExtendExpirationDateResponseDto, 
    BulkResetTrafficUsersRequestDto, 
    BulkResetTrafficUsersResponseDto, 
    BulkResponseData, 
    BulkResponseDto,
    BulkRevokeUsersSubscriptionRequestDto, 
    BulkRevokeUsersSubscriptionResponseDto, 
    BulkUpdateUsersInternalSquadsRequestDto,
    BulkUpdateUsersRequestDto, 
    BulkUpdateUsersResponseDto, 
    BulkUpdateUsersSquadsRequestDto, 
    BulkUpdateUsersSquadsResponseDto, 
    TagStr, 
    UpdateUserFields,
)
from .users_stats import UserUsageByRange, UserUsageByRangeResponseDto
from .xray_config import (
    ConfigResponseDto,  # Legacy alias
    GetConfigResponseDto,
    UpdateConfigRequestDto,
    UpdateConfigResponseDto,
)
from .subscription_request_history import (
    GetAllSubscriptionRequestHistoryResponseDto,
    GetSubscriptionRequestHistoryStatsResponseDto,
    SubscriptionRequestHistoryRecord,
    SubscriptionRequestHistoryData,
    AppStatItem,
    HourlyRequestStat,
    SubscriptionRequestHistoryStatsData
)
from .webhook import (
    UserEventDto,
    UserHwidDeviceEventDto,
    HwidUserDeviceDto,
    LastConnectedNodeDto,
    InternalSquadDto,
    BaseUserDto,
    UserDto,
    NodeDto,
    WebhookNodeConfigProfileDto,
    ConfigProfileInboundDto,
    InfraProviderDto,
    LoginAttemptDto,
    ServiceEventDto,
    NodeEventDto,
    CustomErrorEventDto,
    CrmEventDto,
    TorrentBlockerEventDto,
    TorrentBlockerReportDto,
    WebhookPayloadDto,
    UserTrafficDto,
    NodeSystemDto,
    NodeSystemInfoDto,
    NodeSystemStatsDto,
    NodeSystemInterfaceDto,
    NodeVersionsDto,
)
from .passkeys import (
    DeletePasskeyRequestDto,
    DeletePasskeyResponseDto,
    GetAllPasskeysResponseDto,
    GetPasskeyRegistrationOptionsResponseDto,
    PasskeyDto,
    UpdatePasskeyRequestDto,
    UpdatePasskeyResponseDto,
    VerifyPasskeyRegistrationRequestDto,
    VerifyPasskeyRegistrationResponseDto,
)
from .metadata import (
    GetUserMetadataResponseDto,
    UpsertUserMetadataRequestBodyDto,
    UpsertUserMetadataResponseDto,
    GetNodeMetadataResponseDto,
    UpsertNodeMetadataRequestBodyDto,
    UpsertNodeMetadataResponseDto,
)
from .node_plugins import (
    TorrentBlockerNodeDto,
    TorrentBlockerStatsDto,
    TorrentBlockerTopNodeDto,
    TorrentBlockerTopUserDto,
    TorrentBlockerUserDto,
    CreateSharedListRequestDto,
    CreateSharedListResponseDto,
    DeleteSharedListRequestDto,
    DeleteSharedListResponseDto,
    GetNodePluginsTagsResponseDto,
    GetSharedListResponseDto,
    GetSharedListsResponseDto,
    SetNodePluginsTagsRequestDto,
    SetNodePluginsTagsResponseDto,
    SharedListDto,
    SharedListPreviewDto,
    SyncNodePluginRequestDto,
    SyncSharedListRequestDto,
    UpdateSharedListRequestDto,
    UpdateSharedListResponseDto,
    GetTorrentBlockerReportsResponseDto,
    GetTorrentBlockerReportsStatsResponseDto,
    TruncateTorrentBlockerReportsResponseDto,
    GetNodePluginsResponseDto,
    GetNodePluginResponseDto,
    UpdateNodePluginRequestDto,
    UpdateNodePluginResponseDto,
    DeleteNodePluginResponseDto,
    CreateNodePluginRequestDto,
    CreateNodePluginResponseDto,
    ReorderNodePluginItem,
    ReorderNodePluginsRequestDto,
    ReorderNodePluginsResponseDto,
    CloneNodePluginRequestDto,
    CloneNodePluginResponseDto,
    PluginExecutorRequestDto,
    PluginExecutorResponseDto,
    BlockIpsCommandDto,
    UnblockIpsCommandDto,
    RecreateTablesCommandDto,
    BlockIpItemDto,
    TorrentBlockerReportRecordDto,
    NodePluginDto,
    TargetAllNodesDto,
    TargetSpecificNodesDto,
)
from .external_squads import (
    GetExternalSquadsTagsResponseDto,
    SetExternalSquadsTagsRequestDto,
    SetExternalSquadsTagsResponseDto,
    AddUsersToExternalSquadResponseDto,
    CreateExternalSquadRequestDto,
    CreateExternalSquadResponseDto,
    DeleteExternalSquadResponseDto,
    ExternalSquadDto,
    ExternalSquadInfoDto,
    ExternalSquadSubscriptionSettingsDto,
    ExternalSquadTemplateDto,
    GetExternalSquadByUuidResponseDto,
    GetExternalSquadsResponseDto,
    RemoveUsersFromExternalSquadResponseDto,
    ReorderExternalSquadItem,
    ReorderExternalSquadsRequestDto,
    ReorderExternalSquadsResponseDto,
    TemplateType,
    UpdateExternalSquadRequestDto,
    UpdateExternalSquadResponseDto,
)
from .snippets import (
    SyncSnippetRequestDto,
    CreateSnippetRequestDto,
    CreateSnippetResponseDto,
    DeleteSnippetRequestDto,
    DeleteSnippetResponseDto,
    GetSnippetsResponseDto,
    SnippetItem,
    SnippetsData,
    UpdateSnippetRequestDto,
    UpdateSnippetResponseDto,
)
from .remnawave_settings import (
    BrandingSettings,
    GetRemnawaveSettingsResponseDto,
    GitHubOAuth2Settings,
    GenericOAuth2Settings,
    KeycloakOAuth2Settings,
    OAuth2Settings,
    PasskeySettings,
    PasswordSettings,
    PocketIdOAuth2Settings,
    RemnawaveSettingsData,
    TelegramAuthSettings,
    UpdateRemnawaveSettingsRequestDto,
    UpdateRemnawaveSettingsResponseDto,
    YandexOAuth2Settings,
)
from .subscription_page import (
    GetSubpageConfigsTagsResponseDto,
    SetSubpageConfigsTagsRequestDto,
    SetSubpageConfigsTagsResponseDto,
    CloneSubscriptionPageConfigRequestDto,
    CloneSubscriptionPageConfigResponseDto,
    CreateSubscriptionPageConfigRequestDto,
    CreateSubscriptionPageConfigResponseDto,
    DeleteSubscriptionPageConfigResponseDto,
    GetSubscriptionPageConfigResponseDto,
    GetSubscriptionPageConfigsResponseDto,
    GetSubpageConfigByShortUuidRequestBodyDto,
    GetSubpageConfigByShortUuidResponseDto,
    SubpageConfigData,
    ReorderSubscriptionPageConfigItem,
    ReorderSubscriptionPageConfigsRequestDto,
    ReorderSubscriptionPageConfigsResponseDto,
    SubscriptionPageConfigDto,
    UpdateSubscriptionPageConfigRequestDto,
    UpdateSubscriptionPageConfigResponseDto,
)
from .ip_control import (
    # Request DTOs
    DropConnectionsRequestDto,
    DropByUserUuids,
    DropByIpAddresses,
    TargetAllNodes,
    TargetSpecificNodes,
    # Response DTOs
    FetchIpsResponseDto,
    FetchIpsResultResponseDto,
    FetchUsersIpsResponseDto,
    FetchUsersIpsResultResponseDto,
    DropConnectionsResponseDto,
    # Data models
    FetchIpsJobData,
    FetchIpsProgressData,
    FetchIpsNodeResult,
    FetchIpsResult,
    FetchIpsResultData,
    FetchUsersIpsJobData,
    FetchUsersIpsUserIp,
    FetchUsersIpsUser,
    FetchUsersIpsResult,
    FetchUsersIpsResultData,
    DropConnectionsResponseData,
    # Geocheck (v3.4.0+)
    GeocheckByNodeRequestDto,
    GeocheckByNodeResponseDto,
    GeocheckByNodeResultResponseDto,
    GeocheckImageDto,
    GeocheckJobData,
    GeocheckResult,
    GeocheckResultData,
)
from .node_integrations import (
    CreateNodeIntegrationRequestDto,
    CreateNodeIntegrationResponseDto,
    DeleteNodeIntegrationResponseDto,
    GetNodeIntegrationResponseDto,
    GetNodeIntegrationsResponseDto,
    NodeIntegrationDto,
    UpdateNodeIntegrationRequestDto,
    UpdateNodeIntegrationResponseDto,
)
from .tags import (
    EntityTag,
    GetTagsResponseDto,
    SetTagsRequestDto,
    SetTagsResponseDto,
)

__all__ = [
    # Auth models
    "GetStatusResponseDto",
    "LoginRequestDto",
    "LoginResponseDto",
    "RegisterRequestDto",
    "RegisterResponseDto",
    "StatusResponseDto",  # Legacy alias
    "TelegramCallbackRequestDto",
    "TelegramCallbackResponseDto",
    "LoginTelegramRequestDto",  # Legacy alias
    "OAuth2AuthorizeRequestDto",
    "OAuth2AuthorizeResponseDto",
    "OAuth2CallbackRequestDto",
    "OAuth2CallbackResponseDto",
    "VerifyPasskeyAuthenticationRequestDto",
    "VerifyPasskeyAuthenticationResponseDto",
    "GetPasskeyAuthenticationOptionsResponseDto",
    "BrandingSettings",
    # Nodes models
    "CreateNodeRequestDto",
    "CreateNodeResponseDto",
    "DeleteNodeResponseDto",
    "DisableNodeResponseDto",
    "EnableNodeResponseDto",
    "ExcludedInbounds",
    "GetAllNodesResponseDto",
    "GetAllNodesTagsResponseDto",
    "GetOneNodeResponseDto",
    "NodeResponseDto",
    "NodesResponseDto",  # Legacy alias
    "ReorderNodeRequestDto",
    "ReorderNodeResponseDto",
    "RestartAllNodesResponseDto",
    "RestartNodeResponseDto",
    "UpdateNodeRequestDto",
    "UpdateNodeResponseDto",
    "NodeConfigProfileDto",
    "NodeConfigProfileRequestDto",
    "RestartAllNodesRequestDto",  # Legacy alias
    "RestartAllNodesRequestBodyDto",
    "RestartNodeRequestBodyDto",
    "ResetNodeTrafficRequestDto",
    "ResetNodeTrafficResponseDto",
    "ProfileModificationRequestDto",
    "ProfileModificationResponseDto",
    "NodeBulkActionType",
    "NodesBulkActionsRequestDto",
    "NodesBulkActionsResponseDto",
    "BulkNodesUpdateRequestDto",
    "BulkNodesUpdateFieldsDto",
    "BulkNodesUpdateResponseDto",
    # Hosts models
    "CreateHostRequestDto",
    "CreateHostResponseDto",
    "DeleteHostResponseDto",
    "GetAllHostsResponseDto",
    "GetOneHostResponseDto",
    "HostResponseDto",
    "HostsResponseDto",  # Legacy alias
    "ReorderHostRequestDto",
    "ReorderHostResponseDto",
    "UpdateHostRequestDto",
    "UpdateHostResponseDto",
    "GetAllHostTagsResponseDto",
    "CreateHostInboundData",
    "HostInboundData",
    "ReorderHostItem",
    # Inbounds models
    "AllInboundsData",
    "FullInboundResponseDto",
    "FullInboundStatistic",
    "FullInboundsResponseDto",
    "GetFullInboundsResponseDto",
    "GetInboundsResponseDto",
    "InboundResponseDto",
    "InboundsResponseDto",  # Legacy alias
    "GetInternalSquadAccessibleNodesResponseDto",
    "InboundsByProfileData",
    # Keygen models
    "GetNodeSecretKeyResponseDto",  # Legacy alias
    # Subscription models
    "GetAllSubscriptionsResponseDto",
    "GetSubscriptionByUsernameResponseDto",
    "GetSubscriptionByShortUUIDResponseDto",
    "GetSubscriptionByUUIDResponseDto",
    "GetSubscriptionInfoResponseDto",
    "SubscriptionInfoResponseDto",  # Legacy alias
    "UserSubscription",
    "GetRawSubscriptionByShortUuidResponseDto",
    "RawSettings",
    "GetConnectionKeysByUuidResponseDto",
    # Subscription settings models
    "GetSubscriptionSettingsResponseDto",
    "SubscriptionSettingsResponseDto",
    "UpdateSubscriptionSettingsRequestDto",
    "SubscriptionType",
    "CustomRemarksDto",
    "HwidSettingsDto",
    # Backward compatibility aliases
    "CustomRemarks",
    "HwidSettings",
    "UpdateSubscriptionSettingsResponseDto",
    "ResponseModificationHeader",
    "ResponseModifications",
    "ResponseRule",
    "ResponseRuleCondition",
    "ResponseRules",
    "ResponseRulesSettings",
    # Subscription template models
    "GetTemplateResponseDto",
    "TemplateResponseDto",
    "UpdateTemplateRequestDto",
    "UpdateTemplateResponseDto",
    "CreateSubscriptionTemplateRequestDto",
    "CreateSubscriptionTemplateResponseDto",
    "DeleteSubscriptionTemplateResponseDto",
    "GetTemplatesResponseDto",
    "ReorderTemplateItem",
    "ReorderSubscriptionTemplatesRequestDto",
    "ReorderSubscriptionTemplatesResponseDto",
    "TemplateInfoDto",
    # System models
    "BandwidthStatistic",
    "BandwidthStatisticResponseDto",
    "CPUStatistic",
    "GetBandwidthStatsResponseDto",
    "GetNodesStatisticsResponseDto",
    "GetRemnawaveHealthResponseDto",
    "GetStatsResponseDto",
    "GetStatsDigestResponseDto",
    "GetHttpStatsResponseDto",
    "GetConfigurationResponseDto",
    "ConfigurationNotifications",
    "ConfigurationService",
    "ConfigurationMisc",
    "MemoryStatistic",
    "NodeStatistic",
    "NodesStatisticResponseDto",
    "OnlineStatistic",
    "StatisticResponseDto",
    "StatusCounts",
    "UsersStatistic",
    "GetNodesMetricsResponseDto",
    "GetX25519KeyPairResponseDto",
    "X25519KeyPair",
    "DebugSrrMatcherRequestDto",
    "DebugSrrMatcherResponseDto",
    "GetMetadataResponseDto",
    "GetRecapResponseDto",
    "RecapThisMonth",
    "RecapTotal",
    # XRay config models
    "ConfigResponseDto",  # Legacy alias
    "GetConfigResponseDto",
    "UpdateConfigRequestDto",
    "UpdateConfigResponseDto",
    # HWID models
    "CreateHWIDUser",  # Legacy alias
    "CreateUserHwidDeviceRequestDto",
    "CreateUserHwidDeviceResponseDto",
    "DeleteUserHwidDeviceRequestDto",
    "DeleteUserHwidDeviceResponseDto",
    "GetUserHwidDevicesResponseDto",
    "HWIDDeleteRequest",  # Legacy alias
    "HWIDUserResponseDto",  # Legacy alias
    "HWIDUserResponseDtoList",  # Legacy alias
    "GetHwidStatisticsResponseDto",
    "DeleteUserAllHwidDeviceRequestDto",
    "GetTopUsersByHwidDevicesResponseDto",
    "TopUserByHwidDevicesDto",
    "TopUsersByHwidDevicesData",
    # Bandwidth stats models
    "GetNodeUserUsageByRangeResponseDto",
    "GetNodesRealtimeUsageResponseDto",
    "GetNodesUsageByRangeResponseDto",
    "GetUserUsageByRangeResponseDto",
    "NodeRealtimeUsageResponseDto",
    "NodeUsageResponseDto",
    "NodesRealtimeUsageResponseDto",  # Legacy alias
    "NodesUsageResponseDto",  # Legacy alias
    "GetLegacyStatsUserUsageResponseDto",
    "GetLegacyStatsNodesUsersUsageResponseDto",
    "GetStatsNodesRealtimeUsageResponseDto",
    "GetStatsNodesUsageResponseDto",
    "GetStatsNodeUsersUsageResponseDto",
    "GetStatsNodesUsersUsageRequestDto",
    "GetStatsNodesUsersUsageResponseDto",
    "GetStatsUserUsageResponseDto",
    "LegacyUserUsageItem",
    "LegacyNodeUserUsageItem",
    "NodeRealtimeUsageItem",
    "TopNodeItem",
    "TopUserItem",
    "TopNodesUserItem",
    "NodeSeriesItem",
    "StatsNodesUsageData",
    "StatsNodeUsersUsageData",
    "StatsNodesUsersUsageData",
    "StatsUserUsageData",
    # API Tokens models
    "ApiTokenDto",
    "ApiTokenScopeEndpointDto",
    "ApiTokenScopeResourceDto",
    "CreateApiTokenRequestDto",
    "CreateApiTokenResponseDto",
    "DeleteApiTokenResponseDto",
    "DocsInfoDto",
    "FindAllApiTokensResponseDto",
    "GetApiTokenScopesResponseDto",
    # Inbound bulk actions models
    "AddInboundToNodesResponseDto",
    "AddInboundToUsersResponseDto",
    "RemoveInboundFromNodesResponseDto",
    "RemoveInboundFromUsersResponseDto",
    # Host bulk actions models
    "BulkDeleteHostsResponseDto",
    "BulkDisableHostsResponseDto",
    "BulkEnableHostsResponseDto",
    "UpdateManyHostsRequestDto",
    "UpdateManyHostsResponseDto",
    # Users models
    "CreateUserBodyDto",
    "UpdateUserBodyDto",
    "ExtendUserBodyDto",
    "RevokeUserSubscriptionBodyDto",
    "ResolveUserBodyDto",
    "ResolveUserResponseDto",
    "UserResponseDto",
    "UsersResponseDto",
    "GetUsersResponseDto",
    "GetUsersStreamResponseDto",
    "UsersStreamData",
    "GetUsersTagsResponseDto",
    "TagsResponseDto",
    "GetUserSubscriptionRequestHistoryResponseDto",
    "SubscriptionRequestsResponseData",
    "UserTrafficDto",
    "ActiveInternalSquadDto",
    "SubscriptionRequestRecord",
    "HappCrypto",
    "UserActiveInboundsDto",
    "UserLastConnectedNodeDto",
    # Users bulk actions models
    "BulkAllExtendExpirationDateRequestDto",
    "BulkAllExtendExpirationDateResponseDto",
    "BulkAllResetTrafficUsersResponseDto",
    "BulkAllUpdateUsersRequestDto",
    "BulkAllUpdateUsersResponseDto",
    "BulkDeleteUsersByStatusRequestDto",
    "BulkDeleteUsersByStatusResponseDto",
    "BulkDeleteUsersRequestDto",
    "BulkDeleteUsersResponseDto",
    "BulkEventResponseData",
    "BulkExtendExpirationDateRequestDto",
    "BulkExtendExpirationDateResponseDto",
    "BulkResetTrafficUsersRequestDto",
    "BulkResetTrafficUsersResponseDto",
    "BulkResponseData",
    "BulkResponseDto",
    "BulkRevokeUsersSubscriptionRequestDto",
    "BulkRevokeUsersSubscriptionResponseDto",
    "BulkUpdateUsersInternalSquadsRequestDto",
    "BulkUpdateUsersRequestDto",
    "BulkUpdateUsersResponseDto",
    "BulkUpdateUsersSquadsRequestDto",
    "BulkUpdateUsersSquadsResponseDto",
    "TagStr",
    "UpdateUserFields",
    # Users stats models
    "UserUsageByRange",
    "UserUsageByRangeResponseDto",
    # Config profiles models
    "ConfigProfileDto",
    "CreateConfigProfileRequestDto",
    "CreateConfigProfileResponseDto",
    "DeleteConfigProfileResponseDto",
    "GetAllConfigProfilesResponseDto",
    "GetAllInboundsResponseDto",
    "GetConfigProfileByUuidResponseDto",
    "GetInboundsByProfileUuidResponseDto",
    "InboundDto",
    "NodesProfileDto",
    "ReorderConfigProfileItem",
    "ReorderConfigProfilesRequestDto",
    "ReorderConfigProfilesResponseDto",
    "UpdateConfigProfileRequestDto",
    "UpdateConfigProfileResponseDto",
    "GetAllConfigProfilesResponsePaginated",
    # Infra billing models
    "CreateInfraBillingHistoryRecordRequestDto",
    "CreateInfraBillingHistoryRecordResponseDto", 
    "CreateInfraBillingNodeRequestDto",
    "CreateInfraBillingNodeResponseDto",
    "CreateInfraProviderRequestDto",
    "CreateInfraProviderResponseDto",   
    "DeleteInfraBillingHistoryRecordByUuidResponseDto",  
    "DeleteInfraBillingNodeByUuidResponseDto",  # ПЕРЕИМЕНОВАНА (было DeleteInfraBillingNodeResponseDto)
    "DeleteInfraProviderByUuidResponseDto",  # ПЕРЕИМЕНОВАНА (было DeleteInfraProviderResponseDto)
    "GetInfraBillingHistoryRecordsResponseDto",  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingHistoryResponseDto)
    "GetInfraBillingNodesResponseDto",  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingNodesResponseDto)
    "GetInfraProvidersResponseDto",  # ПЕРЕИМЕНОВАНА (было GetAllInfraProvidersResponseDto)
    "GetInfraBillingHistoryByUuidResponseDto",
    "GetInfraBillingNodeByUuidResponseDto",
    "GetInfraProviderByUuidResponseDto",
    "InfraBillingHistoryDto",
    "InfraBillingNodeDto",
    "InfraProviderDto",
    "NodeDto",
    "UpdateInfraBillingNodeRequestDto",
    "UpdateInfraBillingNodeResponseDto",
    "UpdateInfraProviderRequestDto",
    "UpdateInfraProviderResponseDto",
    "DeleteInfraBillingNodeResponseDto",  # LEGACY
    "DeleteInfraProviderResponseDto",  # LEGACY
    "GetAllInfraBillingHistoryResponseDto",  # LEGACY
    "GetAllInfraBillingNodesResponseDto",  # LEGACY
    "GetAllInfraProvidersResponseDto",  # LEGACY
    # Internal squads models
    "AddUsersToInternalSquadRequestDto",
    "AddUsersToInternalSquadResponseDto",
    "CreateInternalSquadRequestDto",
    "CreateInternalSquadResponseDto",
    "DeleteInternalSquadResponseDto",
    "DeleteUsersFromInternalSquadRequestDto",
    "DeleteUsersFromInternalSquadResponseDto",
    "GetAllInternalSquadsResponseDto",
    "GetInternalSquadByUuidResponseDto",
    "InternalSquadDto",
    "ReorderInternalSquadItem",
    "ReorderInternalSquadsRequestDto",
    "ReorderInternalSquadsResponseDto",
    "UpdateInternalSquadRequestDto",
    "UpdateInternalSquadResponseDto",
    "GetInternalSquadAccessibleNodesResponseDto",
    # Nodes usage history models
    "GetNodeUserUsageByRangeResponseDto",
    "GetNodesUsageByRangeResponseDto",
    "GetUserAccessibleNodesResponseDto",
    "NodeInfoDto",
    "NodeUsageDto",
    "UserUsageDto",
    # Subscription request history models
    "GetAllSubscriptionRequestHistoryResponseDto",
    "GetSubscriptionRequestHistoryStatsResponseDto",
    "SubscriptionRequestHistoryRecord",
    "SubscriptionRequestHistoryData",
    "AppStatItem",
    "HourlyRequestStat", 
    "SubscriptionRequestHistoryStatsData",
    # Webhook models
     # USER
    "LastConnectedNodeDto",
    "InternalSquadDto",
    "BaseUserDto",
    "UserDto",
    "UserEventDto",
    "UserTrafficDto",

    # HWID DEVICES
    "HwidUserDeviceDto",
    "UserHwidDeviceEventDto",

    # SERVICE EVENTS
    "LoginAttemptDto",
    "ServiceEventDto",

    # NODE ENTITIES
    "ConfigProfileInboundDto",
    "InfraProviderDto",
    "NodeDto",
    "WebhookNodeConfigProfileDto",
    "NodeEventDto",

    # ERROR EVENTS
    "CustomErrorEventDto",

    # CRM EVENTS
    "CrmEventDto",

    # TORRENT BLOCKER EVENTS
    "TorrentBlockerEventDto",
    "TorrentBlockerReportDto",

    # NODE SYSTEM/VERSIONS
    "NodeSystemDto",
    "NodeSystemInfoDto",
    "NodeSystemStatsDto",
    "NodeSystemInterfaceDto",
    "NodeVersionsDto",

    # WEBHOOK PAYLOAD
    "WebhookPayloadDto",
    
    # Passkeys models
    "DeletePasskeyRequestDto",
    "DeletePasskeyResponseDto",
    "GetAllPasskeysResponseDto",
    "GetPasskeyRegistrationOptionsResponseDto",
    "PasskeyDto",
    "UpdatePasskeyRequestDto",
    "UpdatePasskeyResponseDto",
    "VerifyPasskeyRegistrationRequestDto",
    "VerifyPasskeyRegistrationResponseDto",
    
    # External squads models
    "AddUsersToExternalSquadResponseDto",
    "CreateExternalSquadRequestDto",
    "CreateExternalSquadResponseDto",
    "DeleteExternalSquadResponseDto",
    "ExternalSquadDto",
    "ExternalSquadInfoDto",
    "ExternalSquadSubscriptionSettingsDto",
    "ExternalSquadTemplateDto",
    "GetExternalSquadByUuidResponseDto",
    "GetExternalSquadsResponseDto",
    "RemoveUsersFromExternalSquadResponseDto",
    "ReorderExternalSquadItem",
    "ReorderExternalSquadsRequestDto",
    "ReorderExternalSquadsResponseDto",
    "TemplateType",
    "UpdateExternalSquadRequestDto",
    "UpdateExternalSquadResponseDto",
    
    # Snippets models

    "CreateSnippetRequestDto",
    "CreateSnippetResponseDto",
    "DeleteSnippetRequestDto",
    "DeleteSnippetResponseDto",
    "GetSnippetsResponseDto",
    "SnippetItem",
    "SnippetsData",
    "UpdateSnippetRequestDto",
    "UpdateSnippetResponseDto",
    
    # Remnawave settings models
    
    "BrandingSettings",
    "GetRemnawaveSettingsResponseDto",
    "GenericOAuth2Settings",
    "GitHubOAuth2Settings",
    "KeycloakOAuth2Settings",
    "OAuth2Settings",
    "PasskeySettings",
    "PasswordSettings",
    "PocketIdOAuth2Settings",
    "RemnawaveSettingsData",
    "TelegramAuthSettings",
    "UpdateRemnawaveSettingsRequestDto",
    "UpdateRemnawaveSettingsResponseDto",
    "YandexOAuth2Settings",
    
    # Subscription page config models
    "CloneSubscriptionPageConfigRequestDto",
    "CloneSubscriptionPageConfigResponseDto",
    "CreateSubscriptionPageConfigRequestDto",
    "CreateSubscriptionPageConfigResponseDto",
    "DeleteSubscriptionPageConfigResponseDto",
    "GetSubscriptionPageConfigResponseDto",
    "GetSubscriptionPageConfigsResponseDto",
    "GetSubpageConfigByShortUuidRequestBodyDto",
    "GetSubpageConfigByShortUuidResponseDto",
    "SubpageConfigData",
    "ReorderSubscriptionPageConfigItem",
    "ReorderSubscriptionPageConfigsRequestDto",
    "ReorderSubscriptionPageConfigsResponseDto",
    "SubscriptionPageConfigDto",
    "UpdateSubscriptionPageConfigRequestDto",
    "UpdateSubscriptionPageConfigResponseDto",

    # IP Control models
    "DropConnectionsRequestDto",
    "DropByUserUuids",
    "DropByIpAddresses",
    "TargetAllNodes",
    "TargetSpecificNodes",
    "FetchIpsResponseDto",
    "FetchIpsResultResponseDto",
    "DropConnectionsResponseDto",
    "FetchIpsJobData",
    "FetchIpsProgressData",
    "FetchIpsNodeResult",
    "FetchIpsResult",
    "FetchIpsResultData",
    "FetchUsersIpsResponseDto",
    "FetchUsersIpsResultResponseDto",
    "FetchUsersIpsJobData",
    "FetchUsersIpsUserIp",
    "FetchUsersIpsUser",
    "FetchUsersIpsResult",
    "FetchUsersIpsResultData",
    "DropConnectionsResponseData",
    
    # Metadata models
    "GetMetadataResponseDto",
    "GetUserMetadataResponseDto",
    "UpsertUserMetadataRequestBodyDto",
    "UpsertUserMetadataResponseDto",
    "GetNodeMetadataResponseDto",
    "UpsertNodeMetadataRequestBodyDto",
    "UpsertNodeMetadataResponseDto",

    # Node plugins models
    "GetTorrentBlockerReportsResponseDto",
    "GetTorrentBlockerReportsStatsResponseDto",
    "TruncateTorrentBlockerReportsResponseDto",
    "GetNodePluginsResponseDto",
    "GetNodePluginResponseDto",
    "UpdateNodePluginRequestDto",
    "UpdateNodePluginResponseDto",
    "DeleteNodePluginResponseDto",
    "CreateNodePluginRequestDto",
    "CreateNodePluginResponseDto",
    "ReorderNodePluginItem",
    "ReorderNodePluginsRequestDto",
    "ReorderNodePluginsResponseDto",
    "CloneNodePluginRequestDto",
    "CloneNodePluginResponseDto",
    "PluginExecutorRequestDto",
    "PluginExecutorResponseDto",
    "BlockIpsCommandDto",
    "UnblockIpsCommandDto",
    "RecreateTablesCommandDto",
    "BlockIpItemDto",
    "TorrentBlockerReportRecordDto",
    "NodePluginDto",
    "TargetAllNodesDto",
    "TargetSpecificNodesDto",

    # ===== Remnawave API v3.4.x =====
    "EntityTag",
    "GetTagsResponseDto",
    "SetTagsRequestDto",
    "SetTagsResponseDto",
    "GetConfigProfilesTagsResponseDto",
    "SetConfigProfilesTagsRequestDto",
    "SetConfigProfilesTagsResponseDto",
    "GetInternalSquadsTagsResponseDto",
    "SetInternalSquadsTagsRequestDto",
    "SetInternalSquadsTagsResponseDto",
    "GetExternalSquadsTagsResponseDto",
    "SetExternalSquadsTagsRequestDto",
    "SetExternalSquadsTagsResponseDto",
    "GetNodePluginsTagsResponseDto",
    "SetNodePluginsTagsRequestDto",
    "SetNodePluginsTagsResponseDto",
    "GetSubpageConfigsTagsResponseDto",
    "SetSubpageConfigsTagsRequestDto",
    "SetSubpageConfigsTagsResponseDto",
    "GetSubscriptionTemplatesTagsResponseDto",
    "SetSubscriptionTemplatesTagsRequestDto",
    "SetSubscriptionTemplatesTagsResponseDto",
    "NodeIntegrationDto",
    "GetNodeIntegrationsResponseDto",
    "GetNodeIntegrationResponseDto",
    "CreateNodeIntegrationRequestDto",
    "CreateNodeIntegrationResponseDto",
    "UpdateNodeIntegrationRequestDto",
    "UpdateNodeIntegrationResponseDto",
    "DeleteNodeIntegrationResponseDto",
    "SharedListDto",
    "SharedListPreviewDto",
    "GetSharedListsResponseDto",
    "GetSharedListResponseDto",
    "CreateSharedListRequestDto",
    "CreateSharedListResponseDto",
    "UpdateSharedListRequestDto",
    "UpdateSharedListResponseDto",
    "DeleteSharedListRequestDto",
    "DeleteSharedListResponseDto",
    "SyncSharedListRequestDto",
    "SyncNodePluginRequestDto",
    "HostTag",
    "HostInternalSquadsDto",
    "HostMapperDto",
    "HostMapperOp",
    "HostMapperCopyOp",
    "HostMapperSetOp",
    "HostMapperUnsetOp",
    "NodeIpDto",
    "GeocheckByNodeRequestDto",
    "GeocheckByNodeResponseDto",
    "GeocheckByNodeResultResponseDto",
    "GeocheckImageDto",
    "GeocheckJobData",
    "GeocheckResult",
    "GeocheckResultData",
    "SyncSnippetRequestDto",
    "ResponseModificationEncryption",
    "PlatformStatItem",
    "RuntimeMetric",
    "TorrentBlockerNodeDto",
    "TorrentBlockerStatsDto",
    "TorrentBlockerTopNodeDto",
    "TorrentBlockerTopUserDto",
    "TorrentBlockerUserDto",
]
